version: '3.3'

services:
  db:
    image: postgis/postgis:12-2.5-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'invisible-db'
    ports:
      - "5432:5432"
    volumes:
      - db-persistance:/var/lib/postgresql/data

  db_admin:
    image: adminer:latest
    ports:
      - "8080:8080"
    depends_on:
      - db

  app:
    build: .
    environment:
      - PYTHON_ENVIRONMENT=local
    command: python manage.py runserver 0.0.0.0:8000
    entrypoint: /start.sh
    volumes:
      - ./src:/code
      - ./poetry/poetry.lock:/poetry.lock
      - ./poetry/pyproject.toml:/pyproject.toml
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db-persistance:
