# Generated by Django 3.2.11 on 2022-03-25 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0002_address_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(default='', max_length=45)),
                ('phone_number', models.CharField(max_length=10)),
                ('facebook_url', models.URLField(blank=True, null=True, verbose_name='Lien vers la page facebook')),
                ('instagram_url', models.URLField(blank=True, null=True, verbose_name='Lien vers la page instagram')),
                ('twitter_url', models.URLField(blank=True, null=True, verbose_name='Lien vers la page twitter')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Adresse Email du marchant')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description du commerçant')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.address')),
                ('logo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Marchand',
            },
        ),
    ]
