# Generated by Django 3.2.11 on 2022-04-23 12:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_event_is_exclusive'),
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationTracker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('type', models.IntegerField(choices=[(0, 'Twitter'), (1, 'Facebook'), (2, 'Phone'), (3, 'Event'), (4, 'Merchant'), (5, 'Instagram')], default=-1, verbose_name='Type de click')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='navigations_trackers', to='event.event')),
                ('merchant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='navigation_trackers', to='merchant.merchant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
