# Generated by Django 3.2.11 on 2022-04-24 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0003_auto_20220423_2324'),
        ('merchant', '0003_auto_20220424_1053'),
    ]

    operations = [
    ]
