# Generated by Django 3.2.11 on 2022-04-25 18:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0004_merge_0003_auto_20220423_2324_0003_auto_20220424_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegularOpening',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('day', models.IntegerField(choices=[(1, 'Lundi'), (2, 'Mardi'), (3, 'Mercredi'), (4, 'Jeudi'), (5, 'Vendredi'), (6, 'Samedi'), (7, 'Dimanche')], default=1, verbose_name='jour')),
                ('start_at', models.TimeField(verbose_name='ouverture')),
                ('end_at', models.TimeField(verbose_name='fermeture')),
                ('merchant', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='regular_openings', to='merchant.merchant', verbose_name='Commerçant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
