# Generated by Django 3.2.11 on 2022-04-26 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0005_regularopening'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regularopening',
            options={'verbose_name': "Horaires d'ouverture"},
        ),
    ]
