# Generated by Django 3.2.11 on 2022-03-19 17:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessibilityCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=20, verbose_name='Nom de la catégorie')),
            ],
            options={
                'verbose_name': "Categorie accésibilité de l'expérience",
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=20, verbose_name='Nom de la catégorie')),
            ],
            options={
                'verbose_name': "Categorie de l'expérience",
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, verbose_name="Nom de l'expérience")),
                ('description', models.TextField(verbose_name=" Courte description de l'expérience")),
                ('difficulty', models.IntegerField(blank=True, choices=[(1, 'Facile'), (2, 'Moyenne'), (3, 'Difficile')], null=True)),
                ('accessibility_categories', models.ManyToManyField(related_name='event', to='event.AccessibilityCategory')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.address')),
                ('categories', models.ManyToManyField(related_name='event', to='event.Category')),
                ('images', models.ManyToManyField(related_name='event', to='common.Image')),
                ('merchant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='merchant.merchant')),
            ],
            options={
                'verbose_name': 'Expérience',
            },
        ),
    ]
