# Generated by Django 3.2.11 on 2022-03-25 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_address_user'),
        ('event', '0002_event_merchant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='accessibility_categories',
            field=models.ManyToManyField(related_name='event', to='event.AccessibilityCategory', verbose_name="Catégorie d'accessibilité"),
        ),
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.address', verbose_name="Adresse de l'événement"),
        ),
        migrations.AlterField(
            model_name='event',
            name='categories',
            field=models.ManyToManyField(related_name='event', to='event.Category', verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(verbose_name="Description de l'expérience"),
        ),
        migrations.AlterField(
            model_name='event',
            name='difficulty',
            field=models.IntegerField(blank=True, choices=[(1, 'Facile'), (2, 'Moyenne'), (3, 'Difficile')], null=True, verbose_name='Difficulté'),
        ),
    ]
