# Generated by Django 3.2.11 on 2022-04-22 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20220325_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_exclusive',
            field=models.BooleanField(default=False, verbose_name='Expérience exclusive'),
        ),
    ]
