# Generated by Django 3.2.11 on 2022-04-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='card_color',
            field=models.TextField(choices=[('#FF7E7E', 'Rose'), ('#A02074', 'Flirt'), ('#CF0063', 'Magenta'), ('#2F789D', 'Blue'), ('#06C7F2', 'Bleu clair'), ('#5B53AE', 'Bleu foncé'), ('#7F20A0', 'Violet'), ('#20A091', 'Vert'), ('#EF9935', 'Orange')], default='#FF7E7E'),
        ),
    ]
