# Generated by Django 3.2.11 on 2022-04-26 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0006_alter_regularopening_options'),
        ('event', '0006_event_card_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='merchant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='merchant.merchant'),
        ),
    ]
