# Generated by Django 3.2.11 on 2022-04-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_connection_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_password_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_password_token_end_validity_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
