# Generated by Django 3.2.11 on 2022-04-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20220325_1359'),
        ('core', '0005_auto_20220421_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(to='event.Event'),
        ),
    ]
