# Generated by Django 3.2.11 on 2022-03-19 17:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('line1', models.CharField(max_length=150, verbose_name="Première ligne d'adresse")),
                ('line2', models.CharField(blank=True, max_length=150, null=True, verbose_name="Deuxième ligne d'adresse")),
                ('zipcode', models.IntegerField(verbose_name='Code postal')),
                ('city', models.CharField(max_length=45, verbose_name='Ville')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Adresse complète',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('src', models.URLField(verbose_name='Url du fichier')),
                ('alt_text', models.CharField(max_length=45)),
                ('type', models.IntegerField(choices=[(1, 'Logo'), (2, 'Banner'), (3, "Image de l'expérience"), (4, "avatar de l'utilisateur")])),
                ('order', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name': 'Image',
            },
        ),
    ]
